# admin pass - superman@fly67
POST http://localhost:7879/auth/admin/login
Content-Type: application/json

{
    "email": "superman@gmail.com",
    "password": "superman@fly67"
}

### add company with manager
Post http://localhost:7879/companies
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImEzNDVjZDFjLTRmOWQtNGRhNS05YWUyLWE2NjEyODkyZjA3YyIsInN1YiI6InN1cGVybWFuQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImV4cCI6MTc2NTMwMzYxNX0.9wgRDN0FoLDlBNg685m610Cs66o03X-2kvFa_pP6rsQ
Content-Type: application/json

{
    "company_name": "super",
    "about": "nothing to talk about it",
    "manager": {
        "name": "Peter",
        "position": "vice president",
        "email": "manager@gmail.com"
    }
}

### add company with manager
PATCH  http://localhost:7879/email_verification
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFkY2JhODJmLTlkNzUtNDY0Mi1iN2UwLWM5MWMwNDMxZDMxNiIsInN1YiI6Im1hbmFnZXJAZ21haWwuY29tIiwicm9sZSI6Ik1hbmFnZXIiLCJleHAiOjE3NjUzMDM2MjR9.aZUHTXthu9RVAK8xzUZcamJp9wyyHsxVj7Xiyh3GnT0
Content-Type: application/json

{
    "password": "new_password"
}
